/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.Stocker.view;

/**
 *
 * @author Tacio
 */
public class TelaUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaUsuario
     */
    public TelaUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jLabel1.setText("Id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(550, 130, 10, 16);

        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 130, 34, 16);

        jLabel3.setText("Cpf");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(115, 240, 19, 16);

        jLabel5.setText("Senha");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(524, 190, 36, 16);

        jLabel6.setText("Login");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 190, 34, 16);

        jLabel4.setText("Celular");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(520, 240, 40, 16);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(566, 185, 315, 26);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(140, 185, 315, 26);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(140, 235, 315, 26);

        jTextField4.setText("jTextField4");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(566, 235, 315, 26);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(566, 125, 68, 26);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(140, 125, 315, 26);

        jButton1.setText("Adicionar");
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 420, 85, 27);

        jButton2.setText("Editar");
        getContentPane().add(jButton2);
        jButton2.setBounds(390, 420, 76, 27);

        jButton3.setText("Buscar");
        getContentPane().add(jButton3);
        jButton3.setBounds(550, 420, 76, 27);

        jButton4.setText("Remover");
        getContentPane().add(jButton4);
        jButton4.setBounds(720, 420, 90, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
