/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.Stocker.view;

import java.util.List;

import com.Stocker.dto.Notification;
import com.Stocker.entity.User;
import com.Stocker.services.NotificationService; 

/**
 *
 * @author Tacio
 */
public class TelaNotificacao extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaNotificação
     */
    private User usuario;
    
    public TelaNotificacao(User usuario) {
        this.usuario = usuario;
        initComponents();
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        NotificationService notificationService = new NotificationService(usuario);
        List<Notification> notificacoes = notificationService.execute();
        jTable1.setModel(new NotificationTableModel(notificacoes));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 30, 760, 406);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
