/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.Stocker.view;

import com.Stocker.entity.Supplier;
import com.Stocker.entity.User;
import com.Stocker.services.SupplierService;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tacio
 */
public class TelaFornecedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaFornecedor
     */
    User usuario; 
    
    private SupplierService supplierService;
    
    public TelaFornecedor(User usuario) {
        initComponents();
        this.usuario = usuario;   
        supplierService = new SupplierService(usuario);
    }
    
    public void pesquisar_fornecedores(){ 
        String nomePesquisa = txt_pesquisa.getText(); 
        SupplierService supplierservice = new SupplierService(usuario);   
        List<Supplier> fornecedores = supplierservice.listSuppliers(nomePesquisa);    
        
        
        //Limpar tabela
        DefaultTableModel modeloTabela = (DefaultTableModel) tbl_fornecedores.getModel();  
        modeloTabela.setRowCount(0);
        
        //Adicionar o resultado a tabela
        for (Supplier fornecedor : fornecedores) {
        modeloTabela.addRow(new Object[]{
            fornecedor.getId(),
            fornecedor.getName(),
            fornecedor.getCnpj()
        });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_pesquisa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_fornecedores = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1295, 695));
        getContentPane().setLayout(null);

        txt_pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pesquisaKeyReleased(evt);
            }
        });
        getContentPane().add(txt_pesquisa);
        txt_pesquisa.setBounds(30, 23, 415, 26);

        jButton1.setText("Pesquisar");
        getContentPane().add(jButton1);
        jButton1.setBounds(451, 23, 84, 27);

        tbl_fornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_fornecedores);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 69, 1228, 160);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 250, 1230, 260);

        jLabel1.setText("Codigo de Barras");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 530, 100, 16);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(150, 530, 220, 26);

        jButton2.setText("Adicionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(150, 600, 100, 27);

        jButton3.setText("Remover");
        getContentPane().add(jButton3);
        jButton3.setBounds(280, 600, 90, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_pesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesquisaKeyReleased
        // TODO add your handling code here:
        pesquisar_fornecedores(); 
    }//GEN-LAST:event_txt_pesquisaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tbl_fornecedores;
    private javax.swing.JTextField txt_pesquisa;
    // End of variables declaration//GEN-END:variables
}
