/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.Stocker.view;
import java.text.SimpleDateFormat;
import java.util.Date;
import com.Stocker.services.ProductService;
import com.Stocker.entity.Product;
import com.Stocker.entity.User;
import com.Stocker.dto.CreateProductDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author Tacio
 */
public class TelaProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaProduto
     */
    User usuario;
    
     private ProductService productService;
    
    public void cadastrarProduto(){
        try{
           String nome = nomeTxt.getText();
           Long barcode = Long.parseLong(barcodeTxt.getText());
           Integer precoCompra = Integer.parseInt(entradaTxt.getText());
           Integer precoVenda = Integer.parseInt(saidaTxt.getText());
           int quantidade = Integer.parseInt(quantTxt.getText());
           
           SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
           Date validade = sdf.parse(validadeTxt.getText());
           
           CreateProductDTO produto = new CreateProductDTO(barcode, nome, precoCompra, precoVenda, quantidade, validade);
           
       
           Product novoProduto = productService.createProduct(produto);
           
           if(novoProduto != null){
               JOptionPane.showMessageDialog(this, "Produto cadastrado!");
               nomeTxt.setText(null);
               barcodeTxt.setText(null);
               entradaTxt.setText(null);
               saidaTxt.setText(null);
               quantTxt.setText(null);
               validadeTxt.setText(null);
           } else {
               JOptionPane.showMessageDialog(this, "Preencha os campos corretamente!", "erro",JOptionPane.ERROR_MESSAGE );
               
           }
                 
        } catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    
    
        
    
    
    public TelaProduto(User usuario) {
        initComponents();
        this.usuario = usuario;
        productService = new ProductService(usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomeTxt = new javax.swing.JTextField();
        entradaTxt = new javax.swing.JTextField();
        quantTxt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        saidaTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        barcodeTxt = new javax.swing.JTextField();
        validadeTxt = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(25, 30, 415, 22);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(446, 30, 75, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(25, 70, 1230, 300);

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(25, 410, 33, 16);

        jLabel3.setText("Valor Entrada");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(31, 465, 70, 16);

        jLabel4.setText("Validade");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(620, 410, 45, 16);

        jLabel5.setText("Estoque");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(620, 460, 42, 20);
        getContentPane().add(nomeTxt);
        nomeTxt.setBounds(65, 405, 350, 22);
        getContentPane().add(entradaTxt);
        entradaTxt.setBounds(110, 460, 172, 22);
        getContentPane().add(quantTxt);
        quantTxt.setBounds(680, 460, 64, 22);

        jButton2.setText("Adicionar");
        jButton2.setToolTipText("");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 580, 81, 23);

        jButton3.setText("Editar");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jButton3);
        jButton3.setBounds(600, 580, 72, 23);

        jButton4.setText("Remover");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(980, 570, 77, 23);

        jLabel2.setText("Valor Saida");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 510, 70, 16);

        saidaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saidaTxtActionPerformed(evt);
            }
        });
        getContentPane().add(saidaTxt);
        saidaTxt.setBounds(100, 510, 180, 22);

        jLabel7.setText("Codigo de Barras");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(570, 510, 110, 16);
        getContentPane().add(barcodeTxt);
        barcodeTxt.setBounds(680, 510, 120, 22);

        validadeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validadeTxtActionPerformed(evt);
            }
        });
        getContentPane().add(validadeTxt);
        validadeTxt.setBounds(680, 410, 190, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cadastrarProduto();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void saidaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saidaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saidaTxtActionPerformed

    private void validadeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validadeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_validadeTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barcodeTxt;
    private javax.swing.JTextField entradaTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField nomeTxt;
    private javax.swing.JTextField quantTxt;
    private javax.swing.JTextField saidaTxt;
    private javax.swing.JTextField validadeTxt;
    // End of variables declaration//GEN-END:variables
}
